#!/usr/bin/env bash

GOOS=linux go build
zip trees.zip ./trees
# --handler is the path to the executable inside the .zip
aws lambda update-function-code \
  --function-name trees \
  --zip-file fileb://trees.zip


rm trees.zip
