#!/usr/bin/env bash

GOOS=linux go build
if [ $? -eq 0 ]; then
    echo build ok
else
    echo build failed
    exit 1
fi

zip trees.zip ./trees
# --handler is the path to the executable inside the .zip
aws lambda update-function-code \
  --function-name trees \
  --zip-file fileb://trees.zip

rm trees
rm trees.zip
