#+TITLE: Sourdough Recipes
Mon 03/30/20
--------------------------------------------------------------------------------

**Bread**

Mix:

+ 50g active starter 
+ 350g warm water
+ 500g bread flour
+ 1 1/2 tsp sea salt (or eyeball by spreading evenly over dough)
+ table spoon of olive oil (optional - I also eyeball this)

Kneed it a bit.
Let sit for 8 to 12 hours or until double in size.

Bake at 450 in dutch oven. Greese with olive oil or place on top of parchment paper.

+ 30 minutes lid on
+ 20 minutes with lid off.

This recipe is inspired from [[https://www.theclevercarrot.com][Emilie's]] excellent book "Artisan Sourdough Made Simple".

**Pizza Dough**
/Makes two large pizzas/

Mix:

+ 100g active starter
+ 414g water
+ 285g all purpose flour
+ 285g bread flour
+ 64g whole wheat flour
+ 16g sea salt

Kneed till firm.

Let sit for 2.5 hours on counter.
During this period fold the dough over a few times every thirty minutes.

Add a bit of olive oil and let sit in covered bowl in fridge over night.

In the morning take the dough out and let it rise all day.

Preheat the oven as hot as it goes and dress the pizza.

Cook time depends on many variables. From my experience, the oven has been set
at 500, and we have used a cookie sheet. It takes about 15 minutes in this case.

Source: https://www.theperfectloaf.com/sourdough-pizza-dough-and-recipes/ 

**Pancakes**

+ 2 cups all-purpose flour
+ 2 teaspoons baking powder
+ 1 teaspoon baking soda
+ 2 tablespoons granulated sugar
+ 1 teaspoon salt
+ 1 cup sourdough starter
+ 1 1/2 cups milk
+ 1 large egg beaten
+ 2 tablespoons vegetable oil

These tasted like normal pancakes. They were nice and fluffy.
I was hoping they would have more of a sourdough taste. I used starter from the fridge when I tried this.
Next time I'll experiment with active starter.

Source: https://www.tastesoflizzyt.com/sourdough-pancakes/

**Thoughts**

I've been baking more now that I'm stuck inside from the corona quarantine.

#+BEGIN_EXPORT html
<script type="text/javascript">
const postNum = 14;
</script>
 #+END_EXPORT
