#+title: Sourdough Recipes
#+date: <2020-03-30 Mon>
#+BEGIN_EXPORT html
<script type="text/javascript">
const postNum = 14;
</script>
 #+END_EXPORT

* Bread
Mix:

+ 50g active starter 
+ 350g warm water
+ 500g bread flour
+ 9g sea salt

Kneed it a bit.  Add a drip of olive oil.  Let sit for 8 to 12 hours
or until double in size.

The dough will be sticky and difficult to work with. Work a bit more
flour in until it starts to take shape. Preheat the oven to 400.

I use a cookie sheet or a pizza stone to bake the bread. Add a dusting
of flour before putting the dough on.

Bake for 50 minutes at 400 on the top rack of the oven.  On the bottom
rack add a sheet with a handful of ice cubes.

This recipe is inspired from [[https://www.theclevercarrot.com][Emilie's]] excellent book "Artisan
Sourdough Made Simple".

* Pizza Dough
This recipe takes 24 hours and makes enough dough for two medium sized
pizzas.

On the first night mix the following:

+ 100g active starter
+ 414g water
+ 285g all purpose flour
+ 285g bread flour
+ 64g whole wheat flour
+ 16g sea salt

Kneed till firm. I like to slap it on the counter.
After kneeding add a dribble of olive oil and wipe it around the dough.

Let it rest for 1-2 hours. Put it in a covered bowl in the fridge
overnight.

In the morning take the dough out and let it rise all day.

Preheat the oven to 500 degrees and dress the pizza.

Cook time depends on many variables. In my experience its usually
about 7 minutes, but keep an eye on it.

[[https://www.theperfectloaf.com/sourdough-pizza-dough-and-recipes/][Original]]
